### ISSUE TITLE
QtWebEngine

### ISSUE THREAD

**Issue by nanjigen** [vedgy/goldendict#2]
Hi

Tried building with `qmake "CONFIG+=use_qtwebengine"`

but after a successful build, got `Could not find QtWebEngineProcess` when trying to run `goldendict` from the terminal.

**Comment by vedgy** [comment]
Which operating system? How did you install the Qt version you build against?

**Comment by vedgy** [comment]
Closing because of no response after almost 2 months. Must have been a Qt installation problem.
