### ISSUE TITLE
[support] custom styling

### ISSUE THREAD

**Issue by omega3** [vedgy/goldendict#3]
Is it possible to apply any custom styling css to your fork or Dark Mode?

**Comment by vedgy** [comment]
Styling works in exactly the same way as in GoldenDict master, except for a small change described in [this comment](https://github.com/goldendict/goldendict/issues/719#issuecomment-1591164209).

Other than that, [these dark theme instructions](https://github.com/goldendict/goldendict/wiki/GoldenDict-Dark-Theme) should work.

If you want to make the dark theme available without any custom steps, please contribute a pull request to [the main GoldenDict repository](https://github.com/goldendict/goldendict). I think a good dark theme pull request is very likely to be merged. Then I'll adapt #1542 to the changes in GoldenDict master.

**Comment by omega3** [comment]
I am sorry but I am not a coder. I don't have such skills. I tested linked theme and followed instructions and it doesn't work. There is no:
Open GoldenDict menu "Preferences... → Interface":
set "Add-on style" to dark-theme;
in this version.

**Comment by vedgy** [comment]
The instructions work in my *goldendict-webengine-pr-git* version (slightly customized with my other PRs not related to themes):

![dark-theme](https://github.com/vedgy/goldendict/assets/5929075/dd56a8ce-5551-49a8-b5d4-ddd8ccc328f2)

The *Add-on style* combobox appears at the bottom of the *Interface* tab only after the css files are placed into `$GD_HOME_DIR/styles/dark-theme/`

My system theme is light, so the interface is not entirely dark. And MediaWiki styling is incomplete (probably fixable in the dark theme's css files).

By the way, the file `qt-style.css` can also be placed in `styles/dark-theme/` to let the user switch between addons and built-in themes easier and be able to override some settings in `$GD_HOME_DIR/qt-style.css`, not only `$GD_HOME_DIR/article-style.css`. I'll edit the dark theme wiki page with this improvement.

**Comment by omega3** [comment]
I see. I had the wrong path. I placed css files in /home/user/.**config**/goldendict/styles/dark-theme/
instead of the path you gave. 
Now it works. Thank you very much.

**Comment by vedgy** [comment]
The path `~/.config/goldendict` is a new alternative to the old `~/.goldendict`. If you rename `~/.goldendict` to something else and restart GoldenDict, `~/.config/goldendict`, `~/.cache/goldendict/index`, `~/.local/share/goldendict` will be used. See #1411.
