### ISSUE TITLE
Request for a new tag/release/tarball

### ISSUE THREAD

**Issue by AngryPhantom** [vedgy/goldendict#4]
Not an issue, actually, but a request to make a release/tarball. I wanted to make a PKGBUILD for myself and your 1.5.0 tarball has the same hashsum as the original. Is it possible? Thank you.

**Comment by AngryPhantom** [comment]
Btw, is qt5-webkit is still a dependency? It is dropped already in Arch.

**Comment by AngryPhantom** [comment]
Never mind, I've figured out already how to make a PKGBUILD. Closing the issue. The question now is about **qt5-webkit**.

**Comment by vedgy** [comment]
Doesn't https://aur.archlinux.org/packages/goldendict-webengine-pr-git work for you? Qt WebKit is not a dependency of the Qt WebEngine version. But the Qt WebKit version is still supported in the _*webkit-or-webengine_ branches. See https://github.com/vedgy/goldendict#building-with-qt-webengine-instead-of-qt-webkit

**Comment by AngryPhantom** [comment]
> Doesn't https://aur.archlinux.org/packages/goldendict-webengine-pr-git work for you?

Oh, didn't know about that one. Thanks!

>See https://github.com/vedgy/goldendict#building-with-qt-webengine-instead-of-qt-webkit

Thank you very much. Cheers!
